sites:
  ssense:
    name: ssense
    scraper_class: SsenseScraper
    base_url_template: "https://www.ssense.com/en-ca/{gender}/{category}.json"
    items_per_page: 120
    categories:
      - [men, belts-suspenders]
      - [men, eyewear]
      - [men, face-masks]
      - [men, gloves]
      - [men, hats]
      - [men, jewelry]
      - [men, keychains]
      - [men, pocket-squares-tie-bars]
      - [men, scarves]
      - [men, socks]
      - [men, ties]
      - [men, towels]
      - [men, wallets-card-holders]
      - [men, watches]
      - [men, bags]
      - [men, jackets-coats]
      - [men, jeans]
      - [men, pants]
      - [men, shirts]
      - [men, shorts]
      - [men, suits-blazers]
      - [men, sweaters]
      - [men, swimwear]
      - [men, tops]
      - [men, underwear-loungewear]
      - [men, shoes]
      - [women, bag-accessories]
      - [women, belts-suspenders]
      - [women, eyewear]
      - [women, face-masks]
      - [women, fine-jewelry]
      - [women, gloves]
      - [women, hats]
      - [women, jewelry]
      - [women, keychains]
      - [women, scarves]
      - [women, socks]
      - [women, tech]
      - [women, wallets-card-holders]
      - [women, bags]
      - [women, activewear]
      - [women, dresses]
      - [women, jackets-coats]
      - [women, jeans]
      - [women, jumpsuits]
      - [women, lingerie]
      - [women, pants]
      - [women, shorts]
      - [women, skirts]
      - [women, sweaters]
      - [women, swimwear]
      - [women, tops]
      - [women, shoes]
  gravitypope:
    name: gravitypope
    scraper_class: GravitypopeScraper
    categories:
      - [mens, clothing]
      - [mens, footwear]
      - [mens, accessories]
      - [womens, clothing]
      - [womens, footwear]
      - [womens, accessories]
    items_per_page: 250